### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

POST https://api.groq.com/openai/v1/chat/completions
Authorization: Bearer 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
Content-Type: application/json

{
  "messages": [
    {
      "role": "user",
      "content": "Explain me what a LLM is and why they're important"
    }
  ],
  "model": "llama3-8b-8192"
}

###

GET http://172.30.1.207:9000/actuator/info
Authorization: Basic admin admin


###