- id: 1
  name: "Maven Thymeleaf"
  projectFolders:
    - folderType: "MavenFolder"
      folderName: ".mvn"
      sourcePath: "data_genesis/maven/.mvn"
      destinationPath: "#{majStart(projectName)}/"

    - folderType: "resourceFolder"
      folderName: "resources"
      sourcePath: "data_genesis/maven/src/main/resources"
      destinationPath: "#{majStart(projectName)}/src/main/"

    - folderType: "staticAssetsFolder"
      folderName: "assets"
      sourcePath: "data_genesis/layout/assets"
      destinationPath: "#{majStart(projectName)}/src/main/resources/static/"

    - folderType: "compiledAssetsFolder"
      folderName: "compiled"
      sourcePath: "data_genesis/layout/compiled"
      destinationPath: "#{majStart(projectName)}/src/main/resources/static/"

    - folderType: "errorTemplateFolder"
      folderName: "error"
      sourcePath: "data_genesis/layout/error"
      destinationPath: "#{majStart(projectName)}/src/main/resources/templates/"

    - folderType: "layoutTemplateFolder"
      folderName: "layout"
      sourcePath: "data_genesis/layout/layout"
      destinationPath: "#{majStart(projectName)}/src/main/resources/templates/"

    - folderType: "templsTemplateFolder"
      folderName: "templs"
      sourcePath: "data_genesis/layout/templs"
      destinationPath: "#{majStart(projectName)}/src/main/resources/templates/"

    ##need to change the location to be able to create maven projects but not with thymeleaf
    ##but for now we're putting it
    - folderType: "thymeleafConfig"
      folderName: "config"
      sourcePath: "data_genesis/layout/config"
      destinationPath: "#{majStart(projectName)}/src/main/java/#{groupLink}/#{lowerCase(projectName)}/"
  projectFilesEdits:
    - fileType: "MainFile"
      fileName: "#{majStart(projectName)}Application"
      extension: "java"
      content: |
        package #{groupLink}.#{lowerCase(projectName)};
        
        import org.springframework.boot.SpringApplication;
        import org.springframework.boot.autoconfigure.SpringBootApplication;
        
        @SpringBootApplication
        public class #{majStart(projectName)}Application {
        {{tab}}public static void main(String[] args) {
        {{tab}}{{tab}}SpringApplication.run(#{majStart(projectName)}Application.class, args);
        {{tab}}}
        }
      destinationPath: "#{majStart(projectName)}/src/main/java/#{groupLink}/#{lowerCase(projectName)}"

    - fileType: "TestFile"
      fileName: "#{majStart(projectName)}ApplicationTests"
      extension: "java"
      content: |
        package #{groupLink}.#{lowerCase(projectName)};
        
        import org.junit.jupiter.api.Test;
        import org.springframework.boot.test.context.SpringBootTest;
        
        @SpringBootTest
        class #{majStart(projectName)}ApplicationTests {
        
        {{tab}}@Test
        {{tab}}void contextLoads() {
        {{tab}}}
        
        }
      destinationPath: "#{majStart(projectName)}/src/test/java/#{groupLink}/#{lowerCase(projectName)}/"

    - fileType: "ApplicationProperties"
      fileName: "application"
      extension: "properties"
      content: |
        spring.application.name=#{lowerCase(projectName)}
        
        server.port=#{projectPort}
        
        # Configuration logs
        logging.level.root=#{logLevel}
        {{#if useDB}}
        logging.level.org.hibernate.SQL=#{logLevel}
        
        # Configuration datasource
        spring.datasource.url=#{databaseUrl}
        spring.datasource.username=#{databaseUsername}
        spring.datasource.password=#{databasePassword}
        
        # Configuration Hibernate
        spring.jpa.hibernate.ddl-auto=#{hibernateDdlAuto}
        spring.jpa.properties.hibernate.format_sql=true
        {{/if}}

      destinationPath: "#{majStart(projectName)}/src/main/resources/"

    - fileType: "Xml"
      fileName: "pom"
      extension: "xml"
      content: |
        <?xml version="1.0" encoding="UTF-8"?>
        <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
        {{tab}}<modelVersion>4.0.0</modelVersion>
        {{tab}}<parent>
        {{tab}}{{tab}}<groupId>org.springframework.boot</groupId>
        {{tab}}{{tab}}<artifactId>spring-boot-starter-parent</artifactId>
        {{tab}}{{tab}}<version>#{frameworkVersion}</version>
        {{tab}}{{tab}}<relativePath/>
        {{tab}}</parent>
        {{tab}}<groupId>#{groupLink}</groupId>
        {{tab}}<artifactId>#{projectName}</artifactId>
        {{tab}}<version>0.0.1-SNAPSHOT</version>
        {{tab}}<name>#{projectName}</name>
        {{tab}}<description>#{projectDescription}</description>
        {{tab}}<url/>
        {{tab}}<licenses>
        {{tab}}{{tab}}<license/>
        {{tab}}</licenses>
        {{tab}}<developers>
        {{tab}}{{tab}}<developer/>
        {{tab}}</developers>
        {{tab}}<scm>
        {{tab}}{{tab}}<connection/>
        {{tab}}{{tab}}<developerConnection/>
        {{tab}}{{tab}}<tag/>
        {{tab}}{{tab}}<url/>
        {{tab}}</scm>
        {{tab}}<properties>
        {{tab}}{{tab}}<java.version>#{languageVersion}</java.version>
        {{tab}}</properties>
        {{tab}}<dependencies>
        {{tab}}{{tab}}{{#each dependencies}}
        {{tab}}{{tab}}<dependency>
        {{tab}}{{tab}}{{tab}}<groupId>#{this.groupId}</groupId>
        {{tab}}{{tab}}{{tab}}<artifactId>#{this.artifactId}</artifactId>
        {{tab}}{{tab}}{{tab}}<version>#{this.version}</version>
        {{tab}}{{tab}}</dependency>{{#if !@last}}{{newline}}{{tab}}{{tab}}{{/if}}{{/each}}
        {{tab}}{{tab}}{{#if useDB}}<dependency>
        {{tab}}{{tab}}{{tab}}<groupId>#{DBgroupId}</groupId>
        {{tab}}{{tab}}{{tab}}<artifactId>#{DBartifactId}</artifactId>
        {{tab}}{{tab}}{{tab}}<version>#{DBversion}</version>
        {{tab}}{{tab}}</dependency>{{/if}}
        {{tab}}</dependencies>
        </project>
      destinationPath: "#{majStart(projectName)}/"

    - fileType: "home"
      fileName: "HomeController"
      extension: "java"
      content: |
        package #{groupLink}.#{lowerCase(projectName)}.controllers;

        import org.springframework.stereotype.Controller;
        import org.springframework.web.bind.annotation.GetMapping;
        import org.springframework.beans.factory.annotation.Autowired;

        @Controller
        public class HomeController {

        {{tab}}@GetMapping
        {{tab}}public String index() {
        {{tab}}    return "index";
        {{tab}}}
        }
      destinationPath: "#{majStart(projectName)}/src/main/java/#{groupLink}/#{lowerCase(projectName)}/controllers/"
    - fileType: "menuHtml"
      fileName: "menu"
      extension: "html"
      content: |
        <!-- Menu -->
        <aside #{aside} id="layout-menu" 
        {{tab}}class="layout-menu menu-vertical menu bg-menu-theme">
        {{tab}}<div class="app-brand demo">
        {{tab}}{{tab}}<a href="/" class="app-brand-link">
        {{tab}}{{tab}}{{tab}}<span class="app-brand-logo demo">
        {{tab}}{{tab}}{{tab}}{{tab}}<img #{logo} 
        {{tab}}{{tab}}{{tab}}{{tab}}{{tab}}alt="Logo" style="width: 45px; height: auto;">
        {{tab}}{{tab}}{{tab}}</span>
        {{tab}}{{tab}}{{tab}}<span class="app-brand-text menu-text fw-bolder ms-2">#{majStart(projectName)} </span>
        {{tab}}{{tab}}</a>

        {{tab}}{{tab}}<a href="javascript:void(0);"
        {{tab}}{{tab}}  class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
        {{tab}}{{tab}}{{tab}}<i class="bx bx-chevron-left bx-sm align-middle"></i>
        {{tab}}{{tab}}</a>
        {{tab}}</div>

        {{tab}}<div class="menu-inner-shadow"></div>

        {{tab}}<div class="menu">
        {{tab}}{{tab}}<ul class="menu-inner py-1">
        {{tab}}{{tab}}{{tab}}<!-- List Menu -->
        {{tab}}{{tab}}{{tab}}<li class="menu-header small text-uppercase">
        {{tab}}{{tab}}{{tab}}{{tab}}<span class="menu-header-text">CRUD</span>
        {{tab}}{{tab}}{{tab}}</li>
        
        {{tab}}{{tab}}{{tab}}<li class="menu-item">
        {{tab}}{{tab}}{{tab}}{{tab}}<a href="javascript:void(0);" class="menu-link menu-toggle">
        {{tab}}{{tab}}{{tab}}{{tab}}{{tab}}<i class="menu-icon tf-icons bx bx-list-plus"></i>
        {{tab}}{{tab}}{{tab}}{{tab}}{{tab}}<div data-i18n="List">List</div>
        {{tab}}{{tab}}{{tab}}{{tab}}</a>

        {{tab}}{{tab}}{{tab}}{{tab}}<ul class="menu-sub">
        {{tab}}{{tab}}{{tab}}{{tab}}{{#each fields}}
        {{tab}}{{tab}}{{tab}}{{tab}}{{tab}}{{tab}}<li class="menu-item">
        {{tab}}{{tab}}{{tab}}{{tab}}{{tab}}{{tab}}<a $[listLink] class="menu-link">
        {{tab}}{{tab}}{{tab}}{{tab}}{{tab}}{{tab}}{{tab}}<div data-i18n="list-#{minStart(this)}">List #{lowerCase(this)}</div>
        {{tab}}{{tab}}{{tab}}{{tab}}{{tab}}{{tab}}</a>
        {{tab}}{{tab}}{{tab}}{{tab}}{{tab}}</li>
        {{tab}}{{tab}}{{tab}}{{tab}}{{/each}}
        {{tab}}{{removeLine}}
        {{tab}}{{tab}}{{tab}}{{tab}}</ul>
        {{tab}}{{tab}}{{tab}}</li>
        {{tab}}{{tab}}</ul>
        {{tab}}</div>
        
        <!-- 
        {{tab}}<div class="container">
        {{tab}}{{tab}}<div class="menu-item">
        {{tab}}{{tab}}{{tab}}<a th:href="@{/logout}" class="menu-link">
        {{tab}}{{tab}}{{tab}}{{tab}}<i class="bx bx-log-out"></i>Log out
        {{tab}}{{tab}}{{tab}}</a>
        {{tab}}{{tab}}</div>
        {{tab}}</div> -->
        
        </aside>
      destinationPath: "#{majStart(projectName)}/src/main/resources/templates/templs/"
  projectFiles:
    - fileType: "GitIgnore"
      fileName: ".gitignore"
      sourcePath: "data_genesis/maven/"
      destinationPath: "#{majStart(projectName)}/"

    - fileType: "Helper"
      fileName: "HELP.md"
      sourcePath: "data_genesis/maven/"
      destinationPath: "#{majStart(projectName)}/"

    - fileType: "Script"
      fileName: "mvnw"
      sourcePath: "data_genesis/maven/"
      destinationPath: "#{majStart(projectName)}/"

    - fileType: "ScriptWin"
      fileName: "mvnw.cmd"
      sourcePath: "data_genesis/maven/"
      destinationPath: "#{majStart(projectName)}/"

    - fileType: "HomeController"
      fileName: "HomeController.java"
      sourcePath: "data_genesis/layout/"
      destinationPath: "#{majStart(projectName)}/src/main/java/#{groupLink}/#{lowerCase(projectName)}/controllers/"

    - fileType: "Index"
      fileName: "index.html"
      sourcePath: "data_genesis/layout/"
      destinationPath: "#{majStart(projectName)}/src/main/resources/templates/"
