-- oracle.sql

SELECT SYS_CONTEXT('USERENV','SESSION_USER') FROM dual;
SELECT SYS_CONTEXT('USERENV','CURRENT_SCHEMA') FROM dual;

CREATE TABLE Departement
(
    DeptID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nom    VARCHAR2(50) NOT NULL
);

CREATE TABLE Employe
(
    EmployeID     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nom           VARCHAR2(50) NOT NULL,
    Prenom        VARCHAR2(50) NOT NULL,
    DateNaissance DATE,
    DeptID        NUMBER,
    FOREIGN KEY (DeptID) REFERENCES Departement (DeptID)
);

INSERT INTO Departement (Nom)
VALUES ('Informatique') ,
    ('Ressources Humaines');

INSERT INTO Employe (Nom, Prenom, DateNaissance, DeptID)
VALUES ('Dupont', 'Jean', TO_DATE('1985-06-15', 'YYYY-MM-DD'), 1) ,
    ('Martin', 'Sophie', TO_DATE('1990-09-23', 'YYYY-MM-DD'), 2)
    ,
    ('Durand', 'Luc', TO_DATE('1978-01-10', 'YYYY-MM-DD'), 1);
