-- oracle.sql

SELECT SYS_CONTEXT('USERENV', 'SESSION_USER')
FROM dual;
SELECT SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')
FROM dual;

CREATE TABLE Department
(
    DepartmentID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name         VARCHAR2(50) NOT NULL
);

CREATE TABLE Employee
(
    EmployeeID   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    LastName     VARCHAR2(50) NOT NULL,
    FirstName    VARCHAR2(50) NOT NULL,
    BirthDate    DATE,
    DepartmentID NUMBER,
    FOREIGN KEY (DepartmentID) REFERENCES Department (DepartmentID)
);

INSERT INTO Department (Name)
VALUES ('Information Technology'), ('Human Resources');

INSERT INTO Employee (LastName, FirstName, BirthDate, DepartmentID)
VALUES ('Dupont', 'Jean', TO_DATE('1985-06-15', 'YYYY-MM-DD'), 1) ,
    ('Martin', 'Sophie', TO_DATE('1990-09-23', 'YYYY-MM-DD'), 2)
    ,
    ('Durand', 'Luc', TO_DATE('1978-01-10', 'YYYY-MM-DD'), 1);
