IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'Cars')
BEGIN
CREATE TABLE Cars
(
    Id INT PRIMARY KEY IDENTITY(1,1),
    Make NVARCHAR(50) NOT NULL,
    Model NVARCHAR(100) NOT NULL,
    Year INT NOT NULL,
    Color NVARCHAR(20) NOT NULL,
    Price DECIMAL(10, 2) NOT NULL
)
END